SCGS.WEB/Controllers/CadastrosController.cs
using SCGS.CORE.Business;
using SCGS.CORE.Entity;
using SCGS.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SCGS.WEB.Controllers
{
    [Authorize(Roles = SCGS.CORE.Security.RoleManager.FUNCIONARIO)]
    public class CadastrosController : Controller
    {
        //
        // GET: /Cadastros/

        public ActionResult Index()
        {
            return View();
        }

        #region Controle de Funcionário

        //
        // GET: /Funcionarios/
        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult Funcionarios()
        {
            List<Funcionario> model = FuncionarioBusiness.ObterTodos();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult SalvarFuncionario(FuncionarioModel model)
        {

            FuncionarioBusiness.Save(model.funcionario);

            return RedirectToAction("Funcionarios");
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult SalvarContato(string idfuncionario, string tipocontato, string contato)
        {
            var funcionario = FuncionarioBusiness.Obter(Convert.ToInt32(idfuncionario));

            if (funcionario != null)
            {

                Contato c = new Contato();
                c.Pessoa = funcionario;

                foreach (TipoContato t in Enum.GetValues(typeof(TipoContato)))
                {
                    if (tipocontato.Equals(t.ToString()))
                        c.Tipo = t;
                }
                c.Valor = contato;

                ContatoBusiness.Save(c);
                var contatos = ContatoBusiness.ObterByPessoa(funcionario).Select(
                    a => new
                    {
                        Contato = a.Valor,
                        TipoContato = a.Tipo.ToString(),
                        Id = a.Id
                    }
                    );

                if (contatos != null)
                {

                    return Json(contatos);
                }

            }
            var error = new
            {
                Error = "Error",
                msg = "Selecione um Usuario"
                };
                return Json(error);

      
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult DeletarFuncionario(int Id)
        {
            var funcionario = FuncionarioBusiness.Obter(Id);
            FuncionarioBusiness.Deletar(funcionario);
            return RedirectToAction("Funcionarios");
        }

        //
        // GET: /Funcionario/
        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult Funcionario()
        {
            return View();
        }

        //
        // GET: /EditarFuncionario/1
        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult EditarFuncionario(int Id)
        {
            Funcionario funcionario = FuncionarioBusiness.Obter(Id);
            TempData["funcionariomodel"] = funcionario;
            return RedirectToAction("FuncionarioForm");
        }

        //
        //POST: /AddAndUpdateFuncionario/

        public ActionResult DeletarContato(string idcontato)
        {
            var contato = ContatoBusiness.Obter(Convert.ToInt32(idcontato));
            ContatoBusiness.Deletar(contato);
            var contatos = ContatoBusiness.ObterByPessoa(contato.Pessoa).Select(
                a => new
                {
                    Contato = a.Valor,
                    TipoContato = a.Tipo.ToString(),
                    Id = a.Id
                }
                );

            if (contatos != null)
            {

                return Json(contatos);
            }

            else
            {
                var error = new
                {
                    Error = "Error"
                };
                return Json(error);

            }

        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult AddOrUpdateFuncionario(FuncionarioModel model)
        {

            var funcionario = model.funcionario;
            funcionario.Cidade = CidadeBusiness.Obter(Convert.ToInt32(model.Cidade));
            var equipe = model.Equipe;
            funcionario.Equipe = EquipeBusiness.Obter(Convert.ToInt32(model.Equipe));
            if (FuncionarioBusiness.Save(funcionario) != null)
            {
                TempData["msg"] = "Funcionario Salvo com sucesso!";

            }
            else
            {
                TempData["msg"] = "Error!";

            }

            return RedirectToAction("Funcionarios");
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.GERENTE)]
        public ActionResult FuncionarioForm()
        {
            var estados = obterEstados();
            ViewBag.Estados = estados;
            var cidades = new List<SelectListItem>();
            cidades.Add(new SelectListItem());
            ViewBag.Cidades = cidades;
            ViewBag.Equipes = obterEquipes();
            FuncionarioModel model = new FuncionarioModel();
             if (TempData["funcionariomodel"] != null){
                 Funcionario funcionario  = TempData["funcionariomodel"] as Funcionario;
                 model.funcionario = funcionario;
                model.contatos = ContatoBusiness.ObterByPessoa(model.funcionario).Count > 0 ? ContatoBusiness.ObterByPessoa(model.funcionario) : new List<Contato>();
            }
            else
            {
                model.contatos = new List<Contato>();
            }
            return View(model);
      
        }

        #endregion




        #region Controller Usuario

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult Usuario()
        {

            return View();
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult UsuarioForm()
        {
            ViewBag.Estados = obterEstados();
            var cidades = new List<SelectListItem>();
            cidades.Add(new SelectListItem());
            ViewBag.Cidades = cidades;
            UsuarioModel model = new UsuarioModel();
            if(TempData["usuariomodel"] != null){
                Usuario usuario = TempData["usuariomodel"] as Usuario;
               // model = iniciarUsuario();
                model.usuario = usuario;
                model.contatoList = ContatoBusiness.ObterByPessoa(usuario) != null ? ContatoBusiness.ObterByPessoa(usuario) : new List<Contato>();
            }
            else{
              model = iniciarUsuario();  
            }
            return View(model);
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        private UsuarioModel iniciarUsuario()
        {
            UsuarioModel model = new UsuarioModel();
            Contato contato = new Contato();
            Endereco endereco = new Endereco();
            Usuario usuario = new Usuario();
            usuario.DataCadastro = DateTime.Now;
            List<Contato> contatos = new List<Contato>();
            List<UsuarioFiliacao> filiacao = new List<UsuarioFiliacao>();
            usuario.Filiacao = filiacao;
            List<Prontuario> prontuarios = new List<Prontuario>();
            usuario.Prontuarios = prontuarios;
            model.contatoList = contatos;
            model.contato = contato;
            model.usuario = usuario;
            model.usuario.Endereco = endereco;

            return model;
        }


        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult DeletarUsuario(int Id)
        {
            var usuario = UsuarioBusiness.Obter(Id);
            UsuarioBusiness.Deletar(usuario);

            return RedirectToAction("Usuarios");
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            var usuario = model.usuario;
            //  model.contato.Usuario = usuario;
            //  Contato contato = model.contato;
            usuario.Endereco.Cidade = null;
            usuario.Endereco = EnderecoBusiness.Save(usuario.Endereco);
            usuario.DataCadastro = DateTime.Now;
            UsuarioBusiness.Save(usuario);
            return RedirectToAction("Usuarios");
        }

        

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult Usuarios()
        {
            List<Usuario> model = UsuarioBusiness.ObterTodos();
            return View(model);
        }

        [Authorize(Roles = SCGS.CORE.Security.RoleManager.AGENTE)]
        public ActionResult EditarUsuario(int Id)
        {
            TempData["usuariomodel"] = UsuarioBusiness.Obter(Id);
            return RedirectToAction("UsuarioForm");
        }

        #endregion



        public ActionResult SalvarContatoUsuario(int idusuario, string tipo, string valor)
        {
            var usuariotemp = UsuarioBusiness.Obter(Convert.ToInt32(idusuario));


            if (usuariotemp != null)
            {

                Contato c = new Contato();
                c.Pessoa = usuariotemp;

                foreach (TipoContato t in Enum.GetValues(typeof(TipoContato)))
                {
                    if (tipo.Equals(t.ToString()))
                        c.Tipo = t;
                }

SCGS.WEB/Controllers/LoginController.cs
using SCGS.CORE.Business;
using SCGS.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SCGS.WEB.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        [HttpGet]
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                if (User.IsInRole(SCGS.CORE.Security.RoleManager.FUNCIONARIO))
                {
                    return Redirect("~/");
                }
            }

            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            HttpContext.Cache.Remove(User.Identity.Name);
            Session.Clear(); Session.Abandon();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Index(string matricula, string senha, bool remember = false)
        {

            Login Retorno = new Login();


            Session.Clear(); Session.Abandon();
            if (!matricula.Equals("99999") && !senha.Equals("admin"))
            { 
                if (FuncionarioBusiness.Autenticar(matricula, senha))
                {
                    Retorno.Redirect = FormsAuthentication.GetRedirectUrl(matricula, remember);
                    Retorno.IsConectado = true;
                    FormsAuthentication.SetAuthCookie(matricula, remember);
                }
                else
                {
                    Retorno.IsConectado = false;
                    Retorno.Mensagem = "Usuário ou senha inválidos.";
                }
            }
            else {
                Retorno.Redirect = FormsAuthentication.GetRedirectUrl(matricula, remember);
                Retorno.IsConectado = true;
                FormsAuthentication.SetAuthCookie(matricula, true);                
            }
                
            
            return Json(Retorno);
        }
    }
}

SCGS.WEB/Controllers/ProntuarioController.cs
using SCGS.CORE.Business;
using SCGS.CORE.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCGS.WEB.Controllers
{
    public class ProntuarioController : Controller
    {
        //
        // GET: /Prontuario/
        private Patogeno patogeno;
        private Usuario usuario;

        public ActionResult Prontuarios()
        {
            List<Prontuario> prontuarios = ProntuarioBusiness.ObterTodos();
            return View(prontuarios);
        }






        public ActionResult SalvarProntuario(Prontuario prontuario)
        {
            PatogenoProntuario pp = new PatogenoProntuario();
            prontuario.DATAPrescricao = DateTime.Now;

            usuario = TempData["usuarioTemp"] as Usuario;
            patogeno = TempData["patogeno"] as Patogeno;

            prontuario.Usuario = prontuario.Usuario == null ? usuario : prontuario.Usuario;

            prontuario.Funcionario = FuncionarioBusiness.ObterByMatricula(User.Identity.Name);
            prontuario = ProntuarioBusiness.Save(prontuario);
            pp.patogeno = patogeno;
            pp.prontuario = prontuario;

            PatogenoProntuarioBusiness.Save(pp);



            return RedirectToAction("Prontuarios");
        }


        public ActionResult Usuario(int Id) {
            usuario = UsuarioBusiness.Obter(Id);
            TempData["usuarioTemp"] = usuario;
            return Json(usuario);
        }




        public ActionResult Patogeno(int Id)
        {
             patogeno = PatogenoBusiness.Obter(Id);
            TempData["patogeno"] = patogeno;
            return Json(patogeno);
        }



      


        public ActionResult CriarProntuario()
        {
            // Depois de implementar a parte de login, os prontuários devem vir do usuário tipo médico ou enfermeiro.
            // Funcionario Medico = User.Identity.ObterFuncionario();
            ViewData["usuarios"] = UsuarioBusiness.ObterTodos();
            ViewData["patogeno"] = PatogenoBusiness.ObterTodos();
            var model = new Prontuario();
            return View("ProntuarioForm", model);
        }



        public ActionResult Edit(int id)
        {
            // Depois de implementar a parte de login, os prontuários devem vir do usuário tipo médico ou enfermeiro.
            // Funcionario Medico = User.Identity.ObterFuncionario();
            ViewData["usuarios"] = UsuarioBusiness.ObterTodos();
            ViewData["patogeno"] = PatogenoBusiness.ObterTodos();
            var model = ProntuarioBusiness.Obter(id);
            return View("ProntuarioForm", model);
        }


        public ActionResult Deletar (int Id)
        {
            var prontuario = ProntuarioBusiness.Obter(Id);

            ProntuarioBusiness.Deletar(prontuario);

            return RedirectToAction("Prontuarios");
        }

        public ActionResult Filtrar(string campo, string valor) {

            // Depois de implementar a parte de login, os prontuários devem vir do usuário tipo médico ou enfermeiro.
            // Funcionario Medico = User.Identity.ObterFuncionario();

            var Prontuarios = ProntuarioBusiness.ObterByParametroUsuario(campo, valor).Select(
                a => new
                {
                    Nome = a.Usuario.Nome,
                    RG = a.Usuario.RG,
                    Pescricao = a.Pescricao,
                    Id = a.Id

                });

            if (Prontuarios != null)
            {

                return Json(Prontuarios);
            }
            else
            {
                var error = new
                {
                    Error = "Error"
                };
                return Json(error);

            }
        }

    }
}

SCGS.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - SISTEMA DE CADASTRO  GERAL DE SAÚDE</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datepicker")
    
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            @Html.Partial("~/Views/Shared/_Top.cshtml")
            
            @Html.Partial("~/Views/Shared/_Menu.cshtml")
          
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()               
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SCGS.WEB/Views/Shared/_LayoutOff.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - SISTEMA DE CADASTRO  GERAL DE SAÚDE</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/login")
    @Styles.Render("~/Content/datepicker")

    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>

    @RenderBody()


    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

SCGS.WEB/Views/Shared/_Menu.cshtml
  <!-- ******MENU PRINCIPAL RESPONSIVO***** -->

<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class="active">
            <a href="@Url.Action("../Home/Index")"><i class="fa fa-fw fa-dashboard"></i>Dashboard</a>
        </li>

        @if (User.IsInRole(SCGS.CORE.Security.RoleManager.GERENTE))
            {
            <li>
                <a href="#" data-toggle="collapse" data-target="#relatorios"><i class="fa fa-fw fa-bar-chart-o"></i>Relatórios <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="relatorios" class="collapse">
                    <li>
                        <a href="@Url.Action("Endemias", "Relatorios")">Endemias</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Consultas", "Relatorios")">Consultas</a>
                    </li>                 
                </ul>
            </li>
        }

        <li>
            <!--<a href="javascript:;" data-toggle="collapse" data-target="#cadastros" aria-expanded="false"><i class="fa fa-fw fa-edit"></i>Cadastros <i class="fa fa-fw fa-caret-down"></i></a> -->
            @if (User.IsInRole(SCGS.CORE.Security.RoleManager.AGENTE))
            {
                <a href="@Url.Action("Usuarios", "Cadastros")"><i class="fa fa-fw fa-user-md"></i>Usuarios</a>
            }
            else if (User.IsInRole(SCGS.CORE.Security.RoleManager.GERENTE))
            {

                <ul id="cadastros" class="collapse">
                    <li>
                        @Html.ActionLink("Funcionarios", "Funcionarios", "Cadastros")
                    </li>
                    @*<li>
                            @Html.ActionLink("Usuários", "Usuarios", "Cadastros")
                        </li>*@
                    <li>
                        @Html.ActionLink("Equipes", "Equipes", "Cadastros")
                    </li>
                    @if (User.IsInRole(SCGS.CORE.Security.RoleManager.GERENTE_GERAL))
                    {
                        <li>
                            @Html.ActionLink("Unidades", "Unidades", "Cadastros")
                        </li>
                    }
                    <li>
                        @Html.ActionLink("Micro Áreas", "MicroArea", "Cadastros")
                    </li>

                </ul>
            }
        </li>
        @if (User.IsInRole(SCGS.CORE.Security.RoleManager.AGENTE))
        {
            <li>
                <a href="#" data-toggle="collapse" data-target="#atendimento" aria-expanded="false"><i class="fa fa-fw fa-edit"></i>Atendimento<i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="atendimento" class="collapse">
                    <li>
                        <a href="@Url.Action("Consulta", "Consulta")"><i class="fa fa-fw fa-stethoscope"></i>Consultas</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Prontuarios", "Prontuario")"><i class="fa fa-fw fa-clipboard"></i>Prontuarios</a>
                    </li>
                </ul>
            </li>
        }

        @if (User.IsInRole(SCGS.CORE.Security.RoleManager.AGENTE) ||
                    User.IsInRole(SCGS.CORE.Security.RoleManager.MEDICO))
        {
            <li>
                <a href="@Url.Action("Patogeno", "Cadastros")"><i class="fa fa-fw fa-clipboard"></i>Patogenos</a>
            </li>
            if (User.IsInRole(SCGS.CORE.Security.RoleManager.AGENTE))
            {
                <li>
                    <a href="@Url.Action("Pedido", "Estoque")"><i class="fa fa-fw fa-eyedropper"></i>Pedido Medicamento</a>
                </li>
            }
        }
        @if (User.IsInRole(SCGS.CORE.Security.RoleManager.FARMACEUTICO))
        {
            <li>
                <a href="@Url.Action("Estoque", "Estoque")"><i class="fa fa-fw fa-medkit"></i>Estoque</a>
            </li>
        }
        @*<li>
                <a href="@Url.Action("Configuracao","Configuracoes")"><i class="fa fa-fw fa-cog"></i>Configurações </a>
            </li>*@
    </ul>
</div>

SCGS.WEB/Views/Shared/_Top.cshtml
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    @if (!User.IsInRole(SCGS.CORE.Security.RoleManager.GERENTE_GERAL) && !User.IsInRole(SCGS.CORE.Security.RoleManager.ADMIN))
    {
    <a class="navbar-brand" href="@Url.Action("Index")">SCGS - @User.ObterFuncionario().Equipe.Unidade.Nome - @User.ObterFuncionario().Equipe.Nome</a>
    }
    else
    {
        <a class="navbar-brand" href="@Url.Action("Index")">
            SCGS
        </a>
    }
</div>


<!-- Top Menu Items -->

<ul class="nav navbar-right top-nav">
 @*   <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i><b class="caret"></b></a>
        <ul class="dropdown-menu message-dropdown">
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>
                                    @User.ObterFuncionario().Nome
                                </strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i>Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Smith</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i>Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>Silveira Julio</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i>Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-footer">
                <a href="#">Read All New Messages</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i><b class="caret"></b></a>
        <ul class="dropdown-menu alert-dropdown">
            <li>
                <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">View All</a>
            </li>
        </ul>
    </li>
*@
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> @User.ObterFuncionario().NomeComTratamento() <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("Logout", "Login")"><i class="fa fa-fw fa-power-off"></i>Log Out</a>
            </li>
        </ul>
    </li>
</ul>